-- Insert Maximally-themed HTML email templates (8-bit, pixelated, red/black)

-- Common HTML template style that will be used across all templates
-- Maximally Brand: Black background, Red accents, Courier New font, pixelated/8-bit aesthetic

INSERT INTO email_templates (name, category, subject, body, placeholders) VALUES

-- 1. Judge Thank You
(
  'Judge Thank You',
  'judges',
  'Thank You for Judging {{event_name}}',
  '<!DOCTYPE html><html><head><meta charset="utf-8"><style>body{margin:0;padding:0;font-family:"Courier New",monospace;background:#000}.container{max-width:600px;margin:0 auto;background:#000;border:4px solid #f00}.header{background:#f00;padding:20px;text-align:center;border-bottom:4px solid #000}.header h1{margin:0;color:#000;font-size:24px;text-transform:uppercase;letter-spacing:2px;text-shadow:2px 2px 0 #fff}.content{padding:30px;color:#fff;background:#000}.pixel-box{border:2px solid #f00;padding:20px;margin:20px 0;background:#1a0000}.pixel-box h2{color:#f00;margin-top:0;font-size:18px;text-transform:uppercase}.detail-row{margin:10px 0;padding:10px;background:#0a0000;border-left:3px solid #f00}.detail-label{color:#f00;font-weight:700;display:inline-block;width:100px}.footer{background:#f00;padding:15px;text-align:center;color:#000;font-size:12px;border-top:4px solid #000}</style></head><body><div class="container"><div class="header"><h1>⚡ MAXIMALLY ⚡</h1></div><div class="content"><h2 style="color:#f00;text-transform:uppercase">Thank You, Judge!</h2><p>Dear <strong style="color:#f00">{{judge_name}}</strong>,</p><p>Thank you for being a judge at <strong>{{event_name}}</strong>! Your expertise and time are invaluable.</p><div class="pixel-box"><h2>📋 Event Details</h2><div class="detail-row"><span class="detail-label">Event:</span> {{event_name}}</div><div class="detail-row"><span class="detail-label">Date:</span> {{event_date}}</div><div class="detail-row"><span class="detail-label">Role:</span> Judge</div></div><p>We appreciate your contribution to the tech community!</p><p style="margin-top:30px"><strong style="color:#f00">— Maximally Team</strong></p></div><div class="footer"><p style="margin:0">MAXIMALLY | Building the Future, One Hackathon at a Time</p></div></div></body></html>',
  '["judge_name", "event_name", "event_date"]'::jsonb
),

-- 2. Judge Application Approved
(
  'Judge Application Approved',
  'judges',
  'Welcome to Maximally Judges Panel!',
  '<!DOCTYPE html><html><head><meta charset="utf-8"><style>body{margin:0;padding:0;font-family:"Courier New",monospace;background:#000}.container{max-width:600px;margin:0 auto;background:#000;border:4px solid #f00}.header{background:#f00;padding:20px;text-align:center;border-bottom:4px solid #000}.header h1{margin:0;color:#000;font-size:24px;text-transform:uppercase;letter-spacing:2px;text-shadow:2px 2px 0 #fff}.content{padding:30px;color:#fff;background:#000}.pixel-box{border:2px solid #f00;padding:20px;margin:20px 0;background:#1a0000}.pixel-box h2{color:#f00;margin-top:0;font-size:18px;text-transform:uppercase}.step{margin:15px 0;padding:15px;background:#0a0000;border-left:4px solid #f00}.step-number{display:inline-block;width:30px;height:30px;background:#f00;color:#000;text-align:center;line-height:30px;font-weight:700;margin-right:10px}.footer{background:#f00;padding:15px;text-align:center;color:#000;font-size:12px;border-top:4px solid #000}</style></head><body><div class="container"><div class="header"><h1>⚡ MAXIMALLY ⚡</h1></div><div class="content"><h2 style="color:#f00;text-transform:uppercase">🎉 Application Approved!</h2><p>Dear <strong style="color:#f00">{{judge_name}}</strong>,</p><p><strong style="color:#f00;font-size:18px">Congratulations!</strong> Your application has been approved.</p><div class="pixel-box"><h2>👤 Your Profile</h2><p><strong style="color:#f00">Name:</strong> {{judge_name}}</p><p><strong style="color:#f00">Expertise:</strong> {{expertise}}</p><p><strong style="color:#f00">LinkedIn:</strong> <a href="{{linkedin_url}}" style="color:#f00">View Profile</a></p></div><div class="pixel-box"><h2>📝 Next Steps</h2><div class="step"><span class="step-number">1</span>Receive event invitations via email</div><div class="step"><span class="step-number">2</span>Review judging criteria before events</div><div class="step"><span class="step-number">3</span>Join our judges community</div></div><p style="margin-top:30px"><strong style="color:#f00">— Maximally Team</strong></p></div><div class="footer"><p style="margin:0">MAXIMALLY | Building the Future, One Hackathon at a Time</p></div></div></body></html>',
  '["judge_name", "expertise", "linkedin_url"]'::jsonb
),

-- 3. Judge Event Invitation
(
  'Judge Event Invitation',
  'judges',
  'Invitation to Judge {{event_name}}',
  '<!DOCTYPE html><html><head><meta charset="utf-8"><style>body{margin:0;padding:0;font-family:"Courier New",monospace;background:#000}.container{max-width:600px;margin:0 auto;background:#000;border:4px solid #f00}.header{background:#f00;padding:20px;text-align:center;border-bottom:4px solid #000}.header h1{margin:0;color:#000;font-size:24px;text-transform:uppercase;letter-spacing:2px;text-shadow:2px 2px 0 #fff}.content{padding:30px;color:#fff;background:#000}.pixel-box{border:2px solid #f00;padding:20px;margin:20px 0;background:#1a0000}.pixel-box h2{color:#f00;margin-top:0;font-size:18px;text-transform:uppercase}.detail-row{margin:10px 0;padding:10px;background:#0a0000;border-left:3px solid #f00}.detail-label{color:#f00;font-weight:700;display:inline-block;width:120px}.button{display:inline-block;padding:12px 24px;background:#f00;color:#000;text-decoration:none;font-weight:700;border:2px solid #000;margin:10px 0;text-transform:uppercase}.footer{background:#f00;padding:15px;text-align:center;color:#000;font-size:12px;border-top:4px solid #000}</style></head><body><div class="container"><div class="header"><h1>⚡ MAXIMALLY ⚡</h1></div><div class="content"><h2 style="color:#f00;text-transform:uppercase">📨 Judge Invitation</h2><p>Dear <strong style="color:#f00">{{judge_name}}</strong>,</p><p>We would like to invite you to be a judge for <strong>{{event_name}}</strong>.</p><div class="pixel-box"><h2>📋 Event Details</h2><div class="detail-row"><span class="detail-label">Event:</span> {{event_name}}</div><div class="detail-row"><span class="detail-label">Date:</span> {{event_date}}</div><div class="detail-row"><span class="detail-label">Time:</span> {{event_time}}</div><div class="detail-row"><span class="detail-label">Venue:</span> {{venue}}</div><div class="detail-row"><span class="detail-label">Teams:</span> {{team_count}}</div></div><p>Please confirm your availability by <strong style="color:#f00">{{rsvp_date}}</strong>.</p><p style="margin-top:30px"><strong style="color:#f00">— Maximally Team</strong></p></div><div class="footer"><p style="margin:0">MAXIMALLY | Building the Future, One Hackathon at a Time</p></div></div></body></html>',
  '["judge_name", "event_name", "event_date", "event_time", "venue", "team_count", "rsvp_date"]'::jsonb
),

-- 4. Sponsor Invitation
(
  'Sponsor Invitation',
  'sponsors',
  'Sponsorship Opportunity: {{event_name}}',
  '<!DOCTYPE html><html><head><meta charset="utf-8"><style>body{margin:0;padding:0;font-family:"Courier New",monospace;background:#000}.container{max-width:600px;margin:0 auto;background:#000;border:4px solid #f00}.header{background:#f00;padding:20px;text-align:center;border-bottom:4px solid #000}.header h1{margin:0;color:#000;font-size:24px;text-transform:uppercase;letter-spacing:2px;text-shadow:2px 2px 0 #fff}.content{padding:30px;color:#fff;background:#000}.pixel-box{border:2px solid #f00;padding:20px;margin:20px 0;background:#1a0000}.pixel-box h2{color:#f00;margin-top:0;font-size:18px;text-transform:uppercase}.benefit{margin:10px 0;padding:10px;background:#0a0000;border-left:3px solid #f00}.benefit:before{content:"✓";color:#f00;font-weight:700;margin-right:10px}.footer{background:#f00;padding:15px;text-align:center;color:#000;font-size:12px;border-top:4px solid #000}</style></head><body><div class="container"><div class="header"><h1>⚡ MAXIMALLY ⚡</h1></div><div class="content"><h2 style="color:#f00;text-transform:uppercase">💼 Sponsorship Opportunity</h2><p>Dear <strong style="color:#f00">{{contact_name}}</strong>,</p><p>We are excited to invite <strong>{{company_name}}</strong> to sponsor <strong>{{event_name}}</strong>.</p><div class="pixel-box"><h2>📊 Event Overview</h2><p><strong style="color:#f00">Event:</strong> {{event_name}}</p><p><strong style="color:#f00">Date:</strong> {{event_date}}</p><p><strong style="color:#f00">Participants:</strong> {{participant_count}}+</p><p><strong style="color:#f00">Venue:</strong> {{venue}}</p></div><div class="pixel-box"><h2>🎯 Sponsorship Benefits</h2><div class="benefit">Brand visibility to {{participant_count}}+ developers</div><div class="benefit">Booth space and networking opportunities</div><div class="benefit">Social media promotion</div><div class="benefit">Logo placement on event materials</div></div><p>Multiple sponsorship tiers available. Let''s discuss!</p><p style="margin-top:30px"><strong style="color:#f00">— Maximally Team</strong></p></div><div class="footer"><p style="margin:0">MAXIMALLY | Building the Future, One Hackathon at a Time</p></div></div></body></html>',
  '["contact_name", "company_name", "event_name", "event_date", "participant_count", "venue"]'::jsonb
),

-- 5. Sponsor Thank You
(
  'Sponsor Thank You',
  'sponsors',
  'Thank You for Sponsoring {{event_name}}',
  '<!DOCTYPE html><html><head><meta charset="utf-8"><style>body{margin:0;padding:0;font-family:"Courier New",monospace;background:#000}.container{max-width:600px;margin:0 auto;background:#000;border:4px solid #f00}.header{background:#f00;padding:20px;text-align:center;border-bottom:4px solid #000}.header h1{margin:0;color:#000;font-size:24px;text-transform:uppercase;letter-spacing:2px;text-shadow:2px 2px 0 #fff}.content{padding:30px;color:#fff;background:#000}.pixel-box{border:2px solid #f00;padding:20px;margin:20px 0;background:#1a0000}.pixel-box h2{color:#f00;margin-top:0;font-size:18px;text-transform:uppercase}.detail-row{margin:10px 0;padding:10px;background:#0a0000;border-left:3px solid #f00}.detail-label{color:#f00;font-weight:700;display:inline-block;width:150px}.footer{background:#f00;padding:15px;text-align:center;color:#000;font-size:12px;border-top:4px solid #000}</style></head><body><div class="container"><div class="header"><h1>⚡ MAXIMALLY ⚡</h1></div><div class="content"><h2 style="color:#f00;text-transform:uppercase">🙏 Thank You!</h2><p>Dear <strong style="color:#f00">{{contact_name}}</strong>,</p><p>Thank you for <strong>{{company_name}}</strong>''s sponsorship of <strong>{{event_name}}</strong>! Your support makes these events possible.</p><div class="pixel-box"><h2>📋 Sponsorship Details</h2><div class="detail-row"><span class="detail-label">Event:</span> {{event_name}}</div><div class="detail-row"><span class="detail-label">Tier:</span> {{tier}}</div><div class="detail-row"><span class="detail-label">Date:</span> {{event_date}}</div></div><div class="pixel-box"><h2>📝 Next Steps</h2><p><strong style="color:#f00">Booth Setup:</strong> Details by {{setup_date}}</p><p><strong style="color:#f00">Marketing Deadline:</strong> {{marketing_deadline}}</p><p><strong style="color:#f00">Event Contact:</strong> {{event_contact}}</p></div><p>We look forward to a successful partnership!</p><p style="margin-top:30px"><strong style="color:#f00">— Maximally Team</strong></p></div><div class="footer"><p style="margin:0">MAXIMALLY | Building the Future, One Hackathon at a Time</p></div></div></body></html>',
  '["contact_name", "company_name", "event_name", "tier", "event_date", "setup_date", "marketing_deadline", "event_contact"]'::jsonb
),

-- 6. Participant Welcome
(
  'Participant Welcome',
  'participants',
  'Welcome to {{event_name}}!',
  '<!DOCTYPE html><html><head><meta charset="utf-8"><style>body{margin:0;padding:0;font-family:"Courier New",monospace;background:#000}.container{max-width:600px;margin:0 auto;background:#000;border:4px solid #f00}.header{background:#f00;padding:20px;text-align:center;border-bottom:4px solid #000}.header h1{margin:0;color:#000;font-size:24px;text-transform:uppercase;letter-spacing:2px;text-shadow:2px 2px 0 #fff}.content{padding:30px;color:#fff;background:#000}.pixel-box{border:2px solid #f00;padding:20px;margin:20px 0;background:#1a0000}.pixel-box h2{color:#f00;margin-top:0;font-size:18px;text-transform:uppercase}.detail-row{margin:10px 0;padding:10px;background:#0a0000;border-left:3px solid #f00}.detail-label{color:#f00;font-weight:700;display:inline-block;width:100px}.button{display:inline-block;padding:12px 24px;background:#f00;color:#000;text-decoration:none;font-weight:700;border:2px solid #000;margin:10px 5px;text-transform:uppercase}.footer{background:#f00;padding:15px;text-align:center;color:#000;font-size:12px;border-top:4px solid #000}</style></head><body><div class="container"><div class="header"><h1>⚡ MAXIMALLY ⚡</h1></div><div class="content"><h2 style="color:#f00;text-transform:uppercase">🎉 Welcome!</h2><p>Hi <strong style="color:#f00">{{participant_name}}</strong>,</p><p>Welcome to <strong>{{event_name}}</strong>! We are thrilled to have you participate.</p><div class="pixel-box"><h2>📋 Event Details</h2><div class="detail-row"><span class="detail-label">Event:</span> {{event_name}}</div><div class="detail-row"><span class="detail-label">Date:</span> {{event_date}}</div><div class="detail-row"><span class="detail-label">Time:</span> {{event_time}}</div><div class="detail-row"><span class="detail-label">Venue:</span> {{venue}}</div><div class="detail-row"><span class="detail-label">Team:</span> {{team_name}}</div></div><div class="pixel-box"><h2>🔗 Important Links</h2><p><a href="{{dashboard_link}}" class="button">Dashboard</a> <a href="{{discord_link}}" class="button">Discord</a></p></div><p>Get ready for an amazing experience!</p><p style="margin-top:30px"><strong style="color:#f00">— Maximally Team</strong></p></div><div class="footer"><p style="margin:0">MAXIMALLY | Building the Future, One Hackathon at a Time</p></div></div></body></html>',
  '["participant_name", "event_name", "event_date", "event_time", "venue", "team_name", "dashboard_link", "discord_link"]'::jsonb
),

-- 7. Participant Reminder
(
  'Participant Reminder',
  'participants',
  'Reminder: {{event_name}} is Tomorrow!',
  '<!DOCTYPE html><html><head><meta charset="utf-8"><style>body{margin:0;padding:0;font-family:"Courier New",monospace;background:#000}.container{max-width:600px;margin:0 auto;background:#000;border:4px solid #f00}.header{background:#f00;padding:20px;text-align:center;border-bottom:4px solid #000}.header h1{margin:0;color:#000;font-size:24px;text-transform:uppercase;letter-spacing:2px;text-shadow:2px 2px 0 #fff}.content{padding:30px;color:#fff;background:#000}.pixel-box{border:2px solid #f00;padding:20px;margin:20px 0;background:#1a0000}.pixel-box h2{color:#f00;margin-top:0;font-size:18px;text-transform:uppercase}.checklist{margin:10px 0;padding:10px;background:#0a0000;border-left:3px solid #f00}.checklist:before{content:"☑";color:#f00;font-weight:700;margin-right:10px}.footer{background:#f00;padding:15px;text-align:center;color:#000;font-size:12px;border-top:4px solid #000}</style></head><body><div class="container"><div class="header"><h1>⚡ MAXIMALLY ⚡</h1></div><div class="content"><h2 style="color:#f00;text-transform:uppercase">⏰ Reminder!</h2><p>Hi <strong style="color:#f00">{{participant_name}}</strong>,</p><p><strong style="color:#f00;font-size:18px">{{event_name}} starts tomorrow!</strong></p><div class="pixel-box"><h2>📋 Event Details</h2><p><strong style="color:#f00">Date:</strong> {{event_date}}</p><p><strong style="color:#f00">Time:</strong> {{event_time}}</p><p><strong style="color:#f00">Venue:</strong> {{venue}}</p><p><strong style="color:#f00">Team:</strong> {{team_name}}</p><p><strong style="color:#f00">Check-in:</strong> {{checkin_time}}</p></div><div class="pixel-box"><h2>🎒 What to Bring</h2><div class="checklist">Laptop and charger</div><div class="checklist">Student ID (if applicable)</div><div class="checklist">Your creativity and enthusiasm!</div></div><p>See you soon!</p><p style="margin-top:30px"><strong style="color:#f00">— Maximally Team</strong></p></div><div class="footer"><p style="margin:0">MAXIMALLY | Building the Future, One Hackathon at a Time</p></div></div></body></html>',
  '["participant_name", "event_name", "event_date", "event_time", "venue", "team_name", "checkin_time"]'::jsonb
),

-- 8. Certificate Ready
(
  'Certificate Ready',
  'participants',
  'Your {{event_name}} Certificate is Ready!',
  '<!DOCTYPE html><html><head><meta charset="utf-8"><style>body{margin:0;padding:0;font-family:"Courier New",monospace;background:#000}.container{max-width:600px;margin:0 auto;background:#000;border:4px solid #f00}.header{background:#f00;padding:20px;text-align:center;border-bottom:4px solid #000}.header h1{margin:0;color:#000;font-size:24px;text-transform:uppercase;letter-spacing:2px;text-shadow:2px 2px 0 #fff}.content{padding:30px;color:#fff;background:#000}.pixel-box{border:2px solid #f00;padding:20px;margin:20px 0;background:#1a0000}.pixel-box h2{color:#f00;margin-top:0;font-size:18px;text-transform:uppercase}.button{display:inline-block;padding:15px 30px;background:#f00;color:#000;text-decoration:none;font-weight:700;border:2px solid #000;margin:20px 0;text-transform:uppercase;font-size:16px}.footer{background:#f00;padding:15px;text-align:center;color:#000;font-size:12px;border-top:4px solid #000}</style></head><body><div class="container"><div class="header"><h1>⚡ MAXIMALLY ⚡</h1></div><div class="content"><h2 style="color:#f00;text-transform:uppercase">🏆 Certificate Ready!</h2><p>Hi <strong style="color:#f00">{{participant_name}}</strong>,</p><p><strong style="color:#f00;font-size:18px">Congratulations!</strong> Your certificate for <strong>{{event_name}}</strong> is now ready.</p><div class="pixel-box"><h2>📜 Certificate Details</h2><p><strong style="color:#f00">Event:</strong> {{event_name}}</p><p><strong style="color:#f00">Achievement:</strong> {{achievement}}</p><p><strong style="color:#f00">Position:</strong> {{position}}</p><p><strong style="color:#f00">Certificate ID:</strong> {{certificate_id}}</p></div><p style="text-align:center"><a href="{{certificate_link}}" class="button">Download Certificate</a></p><p>You can verify your certificate anytime using the certificate ID above.</p><p style="margin-top:30px"><strong style="color:#f00">— Maximally Team</strong></p></div><div class="footer"><p style="margin:0">MAXIMALLY | Building the Future, One Hackathon at a Time</p></div></div></body></html>',
  '["participant_name", "event_name", "achievement", "position", "certificate_id", "certificate_link"]'::jsonb
),

-- 9. Event Announcement
(
  'Event Announcement',
  'general',
  'Announcing {{event_name}} - Register Now!',
  '<!DOCTYPE html><html><head><meta charset="utf-8"><style>body{margin:0;padding:0;font-family:"Courier New",monospace;background:#000}.container{max-width:600px;margin:0 auto;background:#000;border:4px solid #f00}.header{background:#f00;padding:20px;text-align:center;border-bottom:4px solid #000}.header h1{margin:0;color:#000;font-size:24px;text-transform:uppercase;letter-spacing:2px;text-shadow:2px 2px 0 #fff}.content{padding:30px;color:#fff;background:#000}.pixel-box{border:2px solid #f00;padding:20px;margin:20px 0;background:#1a0000}.pixel-box h2{color:#f00;margin-top:0;font-size:18px;text-transform:uppercase}.highlight{margin:10px 0;padding:10px;background:#0a0000;border-left:3px solid #f00}.highlight:before{content:"★";color:#f00;font-weight:700;margin-right:10px}.button{display:inline-block;padding:15px 30px;background:#f00;color:#000;text-decoration:none;font-weight:700;border:2px solid #000;margin:20px 0;text-transform:uppercase;font-size:16px}.footer{background:#f00;padding:15px;text-align:center;color:#000;font-size:12px;border-top:4px solid #000}</style></head><body><div class="container"><div class="header"><h1>⚡ MAXIMALLY ⚡</h1></div><div class="content"><h2 style="color:#f00;text-transform:uppercase">🚀 New Event!</h2><p>We are excited to announce <strong style="color:#f00;font-size:20px">{{event_name}}</strong>!</p><div class="pixel-box"><h2>📋 Event Details</h2><p><strong style="color:#f00">Event:</strong> {{event_name}}</p><p><strong style="color:#f00">Date:</strong> {{event_date}}</p><p><strong style="color:#f00">Venue:</strong> {{venue}}</p><p><strong style="color:#f00">Registration Deadline:</strong> {{registration_deadline}}</p></div><div class="pixel-box"><h2>🎯 What to Expect</h2><div class="highlight">{{prize_pool}} in prizes</div><div class="highlight">Networking with industry experts</div><div class="highlight">Workshops and mentorship</div><div class="highlight">Amazing swag and food</div></div><p style="text-align:center"><a href="{{registration_link}}" class="button">Register Now</a></p><p style="text-align:center;color:#f00;font-weight:700">Limited spots available. Don''t miss out!</p><p style="margin-top:30px"><strong style="color:#f00">— Maximally Team</strong></p></div><div class="footer"><p style="margin:0">MAXIMALLY | Building the Future, One Hackathon at a Time</p></div></div></body></html>',
  '["event_name", "event_date", "venue", "registration_deadline", "prize_pool", "registration_link"]'::jsonb
),

-- 10. Event Results
(
  'Event Results Announcement',
  'general',
  '{{event_name}} Winners Announced!',
  '<!DOCTYPE html><html><head><meta charset="utf-8"><style>body{margin:0;padding:0;font-family:"Courier New",monospace;background:#000}.container{max-width:600px;margin:0 auto;background:#000;border:4px solid #f00}.header{background:#f00;padding:20px;text-align:center;border-bottom:4px solid #000}.header h1{margin:0;color:#000;font-size:24px;text-transform:uppercase;letter-spacing:2px;text-shadow:2px 2px 0 #fff}.content{padding:30px;color:#fff;background:#000}.pixel-box{border:2px solid #f00;padding:20px;margin:20px 0;background:#1a0000}.pixel-box h2{color:#f00;margin-top:0;font-size:18px;text-transform:uppercase}.winner{margin:15px 0;padding:15px;background:#0a0000;border-left:4px solid #f00}.winner-place{display:inline-block;width:40px;height:40px;background:#f00;color:#000;text-align:center;line-height:40px;font-weight:700;margin-right:15px;font-size:18px}.stat{display:inline-block;margin:10px 20px 10px 0}.stat-value{color:#f00;font-size:24px;font-weight:700;display:block}.stat-label{color:#fff;font-size:12px}.footer{background:#f00;padding:15px;text-align:center;color:#000;font-size:12px;border-top:4px solid #000}</style></head><body><div class="container"><div class="header"><h1>⚡ MAXIMALLY ⚡</h1></div><div class="content"><h2 style="color:#f00;text-transform:uppercase">🏆 Winners Announced!</h2><p>Thank you for being part of <strong>{{event_name}}</strong>!</p><div class="pixel-box"><h2>🥇 Winners</h2><div class="winner"><span class="winner-place">1st</span><strong>{{first_place}}</strong></div><div class="winner"><span class="winner-place">2nd</span><strong>{{second_place}}</strong></div><div class="winner"><span class="winner-place">3rd</span><strong>{{third_place}}</strong></div></div><div class="pixel-box"><h2>⭐ Special Mentions</h2><p>{{special_mentions}}</p></div><div class="pixel-box"><h2>📊 Event Stats</h2><div class="stat"><span class="stat-value">{{participant_count}}</span><span class="stat-label">Participants</span></div><div class="stat"><span class="stat-value">{{project_count}}</span><span class="stat-label">Projects</span></div><div class="stat"><span class="stat-value">{{prize_pool}}</span><span class="stat-label">Prize Pool</span></div></div><p>Certificates will be sent to all participants within <strong style="color:#f00">{{certificate_timeline}}</strong>.</p><p>Thank you for making this event a success!</p><p style="margin-top:30px"><strong style="color:#f00">— Maximally Team</strong></p></div><div class="footer"><p style="margin:0">MAXIMALLY | Building the Future, One Hackathon at a Time</p></div></div></body></html>',
  '["event_name", "first_place", "second_place", "third_place", "special_mentions", "participant_count", "project_count", "prize_pool", "certificate_timeline"]'::jsonb
);
